### ISSUE TITLE
Problems with authors in output

### ISSUE THREAD

**Issue by danieltomasz** [hits-mbm-dev/paper-talin-loop#1]
Hi! Great template! Do you consider cleaning it a bit, making some documentation and publishing it (on Zenodo for example)?

I just downloaded it, but I have a problem with getting the authors name rendered in html  in latest quarto `0.9.433` (I will start the issue in quarto repo too)

**Comment by jmbuhr** [comment]
Hi, glad you like it. Yes, once the paper is actually finished and submitted I will make a template. I might wait for the official templating system though: https://github.com/quarto-dev/quarto-cli/discussions/374

What are the advantags of Zenodo over GitHub? I haven't used it.

About the authors: there were some discussions on quarto about making the author metadata more powerful and implementing some standard, I assume something like this was now added and is not compatible with my hacks e.g. on the poster template. But it should make it easier going forward. I will adapt this once I continue work on this paper next week.

**Comment by danieltomasz** [comment]
@jmbuhr  For storing code github is the best,  but Zenodo gives you doi (for example if you want to publish only code without publication, but it depend what you want to make from your work here)
https://www.openaire.eu/zenodo-guide

**Comment by jmbuhr** [comment]
Since I am using my own html template for the poster, it didn't work with the new author formatting. For now I am just declaring the authors in a new yaml field that quarto doesn't use (`custom-authors`): https://github.com/hits-mbm-dev/paper-talin-loop/commit/99fcb22c20d65d6b738a996d7267d6b5db8d29c0

**Comment by danieltomasz** [comment]
@jmbuhr  thanks!  And (How) do you print rendered html to pdf?

**Comment by jmbuhr** [comment]
I used use ctrl+P in the browser. Choose Landscape and A0, no margins, include background images.
Then, depending on your print service manually add print-margins to the final pdf before sending it to them.

**Comment by danieltomasz** [comment]
I am able to use this template, so thanks!
Could you help me with one thing? A standard quatro
```
::: {.column-screen}
![A full screen image](/image.png)
:::
```
doesn't seem to work  when I want to span image through whole column,
I can make it work by either adjusting padding to 0 in `#hero p` or `#hero`, but then the text is zero padded too,
is there a simple way to make it work? which class should I adjust?

**Comment by jmbuhr** [comment]
Quarto uses the `article` layout by default: https://quarto.org/docs/authoring/article-layout.html, but for the poster I am using a custom layout, so the column options are not available (https://quarto.org/docs/output-formats/page-layout.html#custom). So you are going to have to tweak the css to make a figure wider. Try experimenting with the developer tools of your browser: Right click the image and choose `inspect`.

**Comment by jmbuhr** [comment]
A hacky way of doing it would be to give the image negative margins and more width:
![image](https://user-images.githubusercontent.com/17450586/170778262-4ad52c34-71c5-4ea0-877a-92684f1bddb3.png)
A cleaner solution would be to remove the padding from the #hero id and add it only for text paragraphs, specifically excluding paragraphs with an image. I am not entirely sure what the best way of doing this is, since the `:has` selection syntax for css is not released on all browsers yet (https://css-tricks.com/the-css-has-selector/)

**Comment by danieltomasz** [comment]
Thanks, after iterating I am able to use the `margin` hack! With `:has` I wasnt able to get it works.
I will close this issue, in case if I have some question I might open another one, or try to learn more about CSS :)
